default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV["APP_DATABASE_HOST"] %>
  database: postgres
  username: postgres
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  port: 5432
  sslmode: verify-full
  sslrootcert: prod-ca-2021.crt
